system("git remote add origin https://github.com/funklano/libro_bosques.git")
system("git add .")
system('git config --global user.name "Roy Rubio"')
system('git config --global user.email "rrubio106@gmail.com"')
system("git config --global --list")
system('git commit -m "Inicialización del libro"')
system("git push -u origin main")
system("git branch -M main")
system("git push -u origin main")
system("git remote add origin https://github.com/funklano/libro_bosques.git")
system("git push -u origin main")
system("git remote -v")

